# Generated by Django 5.2.12 on 2026-06-26 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('manager', models.ManyToManyField(related_name='%(app_label)s_%(class)s_manager', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
                ('sales_rep', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_sales_rep', to=settings.AUTH_USER_MODEL, verbose_name='representantes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('cnpj_cpf', models.CharField(max_length=18, verbose_name='CNPJ/CPF')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='cadastros.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='IN', max_length=3, verbose_name='tipo')),
                ('payment_method', models.CharField(choices=[('dinheiro', '1 - Dinheiro'), ('pix', '2 - Pix'), ('boleto 30dias', '3 - Boleto(30)'), ('boleto 15dias', '4 - Boleto(15)'), ('boleto 7dias', '5 - Boleto(7)'), ('credito', '6 - Crédito'), ('debido', '7 - Débito'), ('crediario', '8 - Crediário')], default='pix', max_length=20, verbose_name='método de pagamento')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor total')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cadastros.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cadastros.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('sku', models.CharField(max_length=20, verbose_name='SKU')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='cor')),
                ('measure_unit', models.CharField(choices=[('UND', '[UND] Unidade'), ('KIT', '[KIT] Kit'), ('CX6', '[CX6] Caixa com 6 peças'), ('CX7', '[CX7] Caixa com 7 peças'), ('CX8', '[CX8] Caixa com 8 peças')], default='UND', max_length=5, verbose_name='unidade de medida')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='estoque')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='cadastros.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='cadastros.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_orders', to='cadastros.product')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('phone', models.CharField(max_length=11, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
