# Generated by Django 5.2.11 on 2026-04-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.field')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Pix'), ('3', 'Boleto(30)'), ('4', 'Boleto(15)'), ('5', 'Boleto(7)'), ('6', 'Crédito'), ('7', 'Débito'), ('8', 'Crediário')], default='2', max_length=20, verbose_name='Método de Pagamento')),
                ('total_value', models.FloatField(verbose_name='Valor Total')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.company')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.field')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50, verbose_name='Cor')),
                ('unit_value', models.FloatField(verbose_name='Valor Unitario')),
                ('stock', models.PositiveIntegerField(verbose_name='Estoque')),
                ('measure_unit', models.CharField(choices=[('UND', 'Unidade'), ('KIT', 'Kit'), ('CX6', 'Caixa com 6 peças'), ('CX7', 'Caixa com 7 peças'), ('CX8', 'Caixa com 8 peças')], default='UND', max_length=5, verbose_name='Unidade de Medida')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.company')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.field')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=11)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.field')),
            ],
        ),
    ]
