# Generated by Django 5.2.12 on 2026-06-26 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['id'], 'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['name'], 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj_cpf',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00 ou 000.000.000-00', max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='cadastros.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_manager', to=settings.AUTH_USER_MODEL, verbose_name='gerentes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cadastros.client', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cadastros.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='cadastros.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Código único do produto (Stock Keeping Unit)', max_length=20, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='cadastros.order', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_orders', to='cadastros.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(help_text='Apenas números, com DDD. Exemplo: 41999999999', max_length=11, verbose_name='telefone'),
        ),
    ]
