# Generated by Django 5.2.11 on 2026-05-12 03:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='field',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='field',
        ),
        migrations.RemoveField(
            model_name='order',
            name='field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_manager', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_rep',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='representantes'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='IN', max_length=3, null=True, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('1', 'Dinheiro'), ('2', 'Pix'), ('3', 'Boleto(30)'), ('4', 'Boleto(15)'), ('5', 'Boleto(7)'), ('6', 'Crédito'), ('7', 'Débito'), ('8', 'Crediário')], default='2', max_length=20, null=True, verbose_name='método de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('UND', 'Unidade'), ('KIT', 'Kit'), ('CX6', 'Caixa com 6 peças'), ('CX7', 'Caixa com 7 peças'), ('CX8', 'Caixa com 8 peças')], default='UND', max_length=5, verbose_name='unidade de medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor unitário'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ/CPF')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.client'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade')),
                ('unit_value', models.FloatField(blank=True, null=True, verbose_name='valor unitário')),
                ('total_value', models.FloatField(blank=True, null=True, verbose_name='valor total')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
