# Generated by Django 5.2.11 on 2026-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_company_field_remove_user_profile_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('dinheiro', '1 - Dinheiro'), ('pix', '2 - Pix'), ('boleto 30dias', '3 - Boleto(30)'), ('boleto 15dias', '4 - Boleto(15)'), ('boleto 7dias', '5 - Boleto(7)'), ('credito', '6 - Crédito'), ('debido', '7 - Débito'), ('crediario', '8 - Crediário')], default='pix', max_length=20, null=True, verbose_name='método de pagamento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('UND', '[UND] Unidade'), ('KIT', '[KIT] Kit'), ('CX6', '[CX6] Caixa com 6 peças'), ('CX7', '[CX7] Caixa com 7 peças'), ('CX8', '[CX8] Caixa com 8 peças')], default='UND', max_length=5, verbose_name='unidade de medida'),
        ),
    ]
