# Generated by Django 5.2.11 on 2026-08-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto'),
        ),
    ]
