# Generated by Django 5.2.11 on 2026-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_productorder_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='session_name',
            field=models.CharField(blank=True, help_text='Nome curto exibido no cabeçalho da página para identificar a empresa da sessão atual. Se ficar em branco, será usado o nome da empresa.', max_length=30, verbose_name='apelido para sessão'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='OUT', max_length=3, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
